### ISSUE TITLE
Question about the firmware

### ISSUE THREAD

**Issue by mister2212** [wmcmillenjr/Hictop-D3#1]
hello
is it possible to use this firmware on the tenlog d3? to me was said that the printers are identical with board and so on? could you help me with info?

**Comment by wmcmillenjr** [comment]
To the best of my knowledge, Hictop buys their IDEX printers from Tenlog and adds their branding. You can try out the firmware on your printer if you woild like. I do not offer support to help get it working on other printers if there are problems once you have it installed to your printer.
